version: "3.7"
services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse
    restart: unless-stopped
    environment:
      - SYNAPSE_REPORT_STATS=no
    volumes:
      - ./synapse/data:/data               # Synapse 自己用
      - ./mautrix-telegram:/data/mautrix-telegram   # 給 Synapse 讀 TG 註冊檔
      - ./mautrix-discord:/data/mautrix-discord     # 給 Synapse 讀 Discord 註冊檔
    ports:
      - "8008:8008"
      - "8448:8448"
    networks:
      - matrix-net

  mautrix-telegram:
    image: dock.mau.dev/mautrix/telegram:latest
    container_name: mautrix-telegram
    restart: unless-stopped
    depends_on:
      - synapse
    volumes:
      - ./mautrix-telegram:/data
    networks:
      - matrix-net               # ⬅️ 已經有

  mautrix-discord:
    image: dock.mau.dev/mautrix/discord:latest
    container_name: mautrix-discord
    restart: unless-stopped
    depends_on:
      - synapse                  # ⬅️ 加上，確保 Synapse 先起
    volumes:
      - ./mautrix-discord:/data
    networks:
      - matrix-net               # ⬅️ 一定要同一條網路，才能用 http://synapse:8008
networks:
  matrix-net:
    driver: bridge
